spring:
  application:
    name: {APP_NAME}
  datasource:
    url: {DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/dev2dbcotizador}
    username: {DATA_SOURCE_USERNAME}
    password: {DATA_SOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: {PORT}
